[project]
name = "llm-uncertainty-decomp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cyclopts>=4.3.0",
    "dotenv>=0.9.9",
    "openai>=2.11.0",
    "probly>=0.3.1",
    "protobuf>=6.33.4",
    "ruff>=0.14.9",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.2.0",
]
